name: Test

on:
    push:
        branches: [feat/refactor-code]
        paths-ignore:
            - .gitignore

jobs:
    build-and-deploy:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, windows-latest]
                python-version: ["3.7", "3.8", "3.9", "3.10"]
        name: Testing with python ${{ matrix.python-version }} on ${{ matrix.os }}
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools wheel
                  python -m pip install poetry
                  poetry install
                  poetry run pytest tests -sv
